# GitHub Labels Configuration
# This file defines the labels used in the repository

labels:
  # Type labels
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: question
    color: d876e3
    description: Further information is requested
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: wontfix
    color: 000000
    description: This will not be worked on
  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists
  - name: invalid
    color: e4e669
    description: Something is wrong
  - name: "priority: high"
    color: ff0000
    description: High priority issue
  - name: "priority: medium"
    color: ffaa00
    description: Medium priority issue
  - name: "priority: low"
    color: 00ff00
    description: Low priority issue
  - name: "status: in progress"
    color: 1d76db
    description: Work is in progress
  - name: "status: blocked"
    color: ff0000
    description: Blocked by another issue
  - name: "status: ready for review"
    color: 0e8a16
    description: Ready for review 