name: Build and Deploy

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build:
    uses: ./.github/workflows/ci.yml
    with:
      distribution-channel: ${{ github.ref == 'refs/heads/main' && 'stable' || 'beta' }}
      prerelease: ${{ github.ref != 'refs/heads/main' }}
    secrets: inherit 