name: Deploy

on:
  workflow_call:
    inputs:
      app-version:
        required: true
        type: string
      distribution-channel:
        required: true
        type: string
      prerelease:
        required: false
        type: boolean
        default: false

permissions:
  contents: write

env:
  NODE_NO_WARNINGS: 1
  npm_config_audit: false
  npm_config_fund: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{inputs.distribution-channel}}
      url: https://github.com/${{github.repository}}/releases/tag/v${{inputs.app-version}}
    steps:
      - name: Download compiled app
        uses: actions/download-artifact@v4
        with:
          pattern: '*-${{inputs.distribution-channel}}'
          path: dist
          merge-multiple: true

      - name: Remove debug files
        run: rm -f dist/*-debug.yml
        shell: bash

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{inputs.app-version}}
          prerelease: ${{inputs.prerelease}}
          artifacts: dist/*.*
          commit: ${{github.sha}}
          allowUpdates: true
          generateReleaseNotes: true
